2018-11-03 14:11:19-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:10:19.098422', 'stop', 'error', 'live', '2018-11-03 14:10:19.098422', 'stop', 'live', '2018-11-03 14:10:19.098422']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:10:19.098422', 'stop', 'error', 'live', '2018-11-03 14:10:19.098422', 'stop', 'live', '2018-11-03 14:10:19.098422']))
2018-11-03 14:13:23-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:12:23.550001', 'stop', 'error', 'live', '2018-11-03 14:12:23.550001', 'stop', 'live', '2018-11-03 14:12:23.550001']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:12:23.550001', 'stop', 'error', 'live', '2018-11-03 14:12:23.550001', 'stop', 'live', '2018-11-03 14:12:23.550001']))
2018-11-03 14:13:54-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:12:54.704098', 'stop', 'error', 'live', '2018-11-03 14:12:54.704098', 'stop', 'live', '2018-11-03 14:12:54.704098']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:12:54.704098', 'stop', 'error', 'live', '2018-11-03 14:12:54.704098', 'stop', 'live', '2018-11-03 14:12:54.704098']))
2018-11-03 14:18:37-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:17:37.522627', 'stop', 'error', 'live', '2018-11-03 14:17:37.522627', 'stop', 'live', '2018-11-03 14:17:37.522627']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:17:37.522627', 'stop', 'error', 'live', '2018-11-03 14:17:37.522627', 'stop', 'live', '2018-11-03 14:17:37.522627']))
2018-11-03 14:18:45-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:17:45.767231', 'stop', 'error', 'live', '2018-11-03 14:17:45.767231', 'stop', 'live', '2018-11-03 14:17:45.767231']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:17:45.767231', 'stop', 'error', 'live', '2018-11-03 14:17:45.767231', 'stop', 'live', '2018-11-03 14:17:45.767231']))
2018-11-03 14:19:24-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:18:24.883614', 'stop', 'error', 'live', '2018-11-03 14:18:24.883614', 'stop', 'live', '2018-11-03 14:18:24.883614']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:18:24.883614', 'stop', 'error', 'live', '2018-11-03 14:18:24.883614', 'stop', 'live', '2018-11-03 14:18:24.883614']))
2018-11-03 14:20:05-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:19:05.910071', 'stop', 'error', 'live', '2018-11-03 14:19:05.910071', 'stop', 'live', '2018-11-03 14:19:05.910071']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:19:05.910071', 'stop', 'error', 'live', '2018-11-03 14:19:05.910071', 'stop', 'live', '2018-11-03 14:19:05.910071']))
2018-11-03 14:20:36-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:19:36.060880', 'stop', 'error', 'live', '2018-11-03 14:19:36.060880', 'stop', 'live', '2018-11-03 14:19:36.060880']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:19:36.060880', 'stop', 'error', 'live', '2018-11-03 14:19:36.060880', 'stop', 'live', '2018-11-03 14:19:36.060880']))
2018-11-03 14:23:14-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:21:43.197380', 'stop', 'error', 'live', '2018-11-03 14:21:43.197380', 'stop', 'live', '2018-11-03 14:21:43.197380']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:21:43.197380', 'stop', 'error', 'live', '2018-11-03 14:21:43.197380', 'stop', 'live', '2018-11-03 14:21:43.197380']))
2018-11-03 14:23:55-ERROR [base.py:process_exception():5]: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:22:23.256722', 'stop', 'error', 'live', '2018-11-03 14:22:23.256722', 'stop', 'live', '2018-11-03 14:22:23.256722']))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thangdinh/Projects/VMS/src/server/api/v1/systems.py", line 20, in get_ai_camera_streaming_status
    return system_manager.get_ai_camera_streaming_status()
  File "/Users/thangdinh/Projects/VMS/src/server/bus/system_manager.py", line 137, in get_ai_camera_streaming_status
    StreamingStatus.STOP, StreamingStatus.LIVE, before1mins]) \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/orm/builder.py", line 1160, in call
    result = attribute(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not enough arguments for format string (SQL: SELECT COUNT(*) AS aggregate FROM `cameras` WHERE 
               enabled = %s AND human_tracking_enabled = %s AND 
               (pipeline_status = %s or pipeline_status = %s or (pipeline_status = %s and pipeline_status_updated_at <= %s) or 
                streaming_status = %s or streaming_status = %s or (streaming_status = %s and streaming_status_updated_at <= %s) or
                ml_streaming_status = %s or (ml_streaming_status = %s and ml_streaming_status_updated_at < %s)) ([True, 'disconnected', 'error', 'connected', '2018-11-03 14:22:23.256722', 'stop', 'error', 'live', '2018-11-03 14:22:23.256722', 'stop', 'live', '2018-11-03 14:22:23.256722']))
